# Generated by Django 4.1.7 on 2023-02-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nac',
            field=models.CharField(max_length=50),
        ),
    ]
